name: Test Notifications

on:
  workflow_run:
    workflows: ["Playwright Tests", "Docker Tests", "Performance Tests"]
    types:
      - completed

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Get workflow run info
      id: workflow-info
      run: |
        echo "workflow_name=${{ github.event.workflow_run.name }}" >> $GITHUB_OUTPUT
        echo "workflow_status=${{ github.event.workflow_run.conclusion }}" >> $GITHUB_OUTPUT
        echo "workflow_url=${{ github.event.workflow_run.html_url }}" >> $GITHUB_OUTPUT
        echo "branch_name=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_OUTPUT

    - name: Notify Slack on Success
      if: github.event.workflow_run.conclusion == 'success'
      uses: 8398a7/action-slack@v3
      with:
        status: success
        fields: repo,message,commit,author,action,eventName,ref,workflow
        text: |
          ✅ *${{ steps.workflow-info.outputs.workflow_name }}* completed successfully!

          📋 *Details:*
          • Branch: `${{ steps.workflow-info.outputs.branch_name }}`
          • Commit: ${{ github.event.workflow_run.head_sha }}
          • Author: ${{ github.event.workflow_run.head_commit.author.name }}

          🔗 [View Results](${{ steps.workflow-info.outputs.workflow_url }})
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Notify Slack on Failure
      if: github.event.workflow_run.conclusion == 'failure'
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        fields: repo,message,commit,author,action,eventName,ref,workflow
        text: |
          🚨 *${{ steps.workflow-info.outputs.workflow_name }}* failed!

          📋 *Details:*
          • Branch: `${{ steps.workflow-info.outputs.branch_name }}`
          • Commit: ${{ github.event.workflow_run.head_sha }}
          • Author: ${{ github.event.workflow_run.head_commit.author.name }}

          🔗 [View Results](${{ steps.workflow-info.outputs.workflow_url }})

          Please check the logs and fix the failing tests.
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  notify-teams:
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Notify Microsoft Teams
      uses: skitionek/notify-microsoft-teams@master
      if: always()
      with:
        webhook_url: ${{ secrets.TEAMS_WEBHOOK_URL }}
        overwrite: "{title: `Test Results: ${{ github.event.workflow_run.name }}`, text: `Status: ${{ github.event.workflow_run.conclusion }}`, themeColor: `${{ github.event.workflow_run.conclusion == 'success' && '00FF00' || 'FF0000' }}`}"

  create-issue-on-failure:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.head_branch == 'main'
    steps:
    - name: Create issue for main branch failures
      uses: actions/github-script@v7
      with:
        script: |
          const title = `🚨 Test Failure on Main Branch - ${context.payload.workflow_run.name}`;
          const body = `
          ## Test Failure Report

          **Workflow:** ${context.payload.workflow_run.name}
          **Branch:** ${context.payload.workflow_run.head_branch}
          **Commit:** ${context.payload.workflow_run.head_sha}
          **Author:** ${context.payload.workflow_run.head_commit.author.name}
          **Run URL:** ${context.payload.workflow_run.html_url}

          ### Description
          The automated tests failed on the main branch. This requires immediate attention.

          ### Next Steps
          - [ ] Review the failed test logs
          - [ ] Identify the root cause
          - [ ] Create a fix
          - [ ] Verify the fix works
          - [ ] Close this issue

          ### Labels
          - bug
          - critical
          - test-failure
          `;

          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: title,
            body: body,
            labels: ['bug', 'critical', 'test-failure']
          });